/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.referenceapp.hishopping.data.clouddb.model;

import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Order.
 *
 * @since 2023-09-25
 */
@PrimaryKeys({"id"})
@Indexes({"userLng:userLng", "date:date", "address:address", "productId:productId", "storeLat:storeLat", "productPhotoUrl:productPhotoUrl", "storeId:storeId", "userId:userId", "userLat:storeLat", "addressId:addressId", "productTitle:productTitle", "id:id", "storeLng:storeLng", "status:status"})
public final class Order extends CloudDBZoneObject {
    private String id;

    private String productId;

    private String userId;

    private String addressId;

    private Integer status;

    private Long date;

    private String storeId;

    private String productPhotoUrl;

    private String productTitle;

    private String address;

    private Double userLat;

    private Double userLng;

    private Double storeLat;

    private Double storeLng;

    public Order() {
        super(Order.class);
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductId() {
        return productId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserId() {
        return userId;
    }

    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    public String getAddressId() {
        return addressId;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getStatus() {
        return status;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public Long getDate() {
        return date;
    }

    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setProductPhotoUrl(String productPhotoUrl) {
        this.productPhotoUrl = productPhotoUrl;
    }

    public String getProductPhotoUrl() {
        return productPhotoUrl;
    }

    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }

    public String getProductTitle() {
        return productTitle;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress() {
        return address;
    }

    public void setUserLat(Double userLat) {
        this.userLat = userLat;
    }

    public Double getUserLat() {
        return userLat;
    }

    public void setUserLng(Double userLng) {
        this.userLng = userLng;
    }

    public Double getUserLng() {
        return userLng;
    }

    public void setStoreLat(Double storeLat) {
        this.storeLat = storeLat;
    }

    public Double getStoreLat() {
        return storeLat;
    }

    public void setStoreLng(Double storeLng) {
        this.storeLng = storeLng;
    }

    public Double getStoreLng() {
        return storeLng;
    }

}
