/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.referenceapp.hishopping.data.clouddb.model;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Product.
 *
 * @since 2023-09-25
 */
@PrimaryKeys({"id"})
@Indexes({"videoUrl:videoUrl", "oldPrice:oldPrice", "price:price", "brandId:brandId", "id:id", "storeId:storeId", "title:title", "arSupported:arSupported", "categoryId:categoryId"})
public final class Product extends CloudDBZoneObject {
    private String id;

    private String brandId;

    private Double price;

    private String title;

    private String videoUrl;

    private Double oldPrice;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean arSupported;

    private String categoryId;

    private String storeId;

    private Text description;

    public Product() {
        super(Product.class);
        this.arSupported = false;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    public String getBrandId() {
        return brandId;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getPrice() {
        return price;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setOldPrice(Double oldPrice) {
        this.oldPrice = oldPrice;
    }

    public Double getOldPrice() {
        return oldPrice;
    }

    public void setArSupported(Boolean arSupported) {
        this.arSupported = arSupported;
    }

    public Boolean getArSupported() {
        return arSupported;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryId() {
        return categoryId;
    }

    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setDescription(Text description) {
        this.description = description;
    }

    public Text getDescription() {
        return description;
    }

}
